matrix:
  dist: trusty
  addons:
    sonarcloud:
      organization: "fanni111-github"
      token:
        secure: b8f70f4226c24fef2193e45b54dcf6c327f0dd09
        
  include:
    - language: java

      jdk: oraclejdk8
      name: "Java server"
      install:
      - mvn -N io.takari:maven:wrapper
      - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      branches:

      script:
      - ./mvnw test -B
      - sonar-scanner
      #- mvn sonar:sonar \
      # -Dsonar.projectKey=Fanni111_Worktable \
      # -Dsonar.organization=fanni111-github \
      # -Dsonar.host.url=https://sonarqube.com \
      # -Dsonar.login=b8f70f4226c24fef2193e45b54dcf6c327f0dd09

      after_script:
      #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
      -  javadoc -d "./doc/backend" -sourcepath src/main/java -subpackages .

    - language: node_js
      node_js:
      - "9"
      name: "Frontend"
      dist: trusty
      sudo: required
      branches:
        only:
        - frontend_development
      before_script:
      - npm install -g @angular/cli
