matrix:
  include:
  - language: java
    jdk: oraclejdk8
    name: Java server
    addons:
      sonarcloud:
        organization: fanni111-github
        token:
           secure: "CH7WF6S0reIZE2vneqDF7lUjUrNNYadpodaw5CFfVWZ2Lw/nEfXOZ3u/S6R7Muvki2kltqdM6MdkdK/Q62QYwUbGOJs+i+v08cf2MgWkVxh4+Gs+p5fKexuFvKbUU1PXHBDi0mHwkXHFi6/iRgRloD0j/eDCrh9ECNLxUiaw8dZWstx3SII8iwr2V1WycKla31mpxAZ2vP/8LUXPd7+4qgjjW7z1Ew5V5WhwNT+2H46RrCx+hIotlreMhZ2D/lQTD0gv0fD2+ZoR9T/j5DyQBTO0YNLV8bBbfvF2UeTgwZCQh6+WFLJ0z23mp+/ZIkyxD4FwgK2BBdx2bpxtqcYerX9nyCWwRt6gHs2PXwvxG1+AaVEHXpsTru9LuhDs+/CaEgD1jfd+hdbkrNOw1SFr66msvkk2m2fFDg+Xny2fSryDxqh7B7BhK01ccdcPnjm3z7n71I2vxrQBwO7t4CHw5s7by7kYOGpQ1hK1svXqkFNZR+IuNqB6/dvnhGNytsdYovhwZgZuW4i7vBniWjkBZlRZ5DYlNY26alHZqiuwJsEw7kt5bBfpXV1ccpulmCOPIrLZ54E311E6DMg82QVMyBpFYmW5GVzy/AX+A3JdMNcB6B9nF69x66DrsNovJtzKR+92ZFsWvnPhw6O0RGQFI6/0bH+C2LfgX/aQRYOjSgQ="
    install:
    - mvn -N io.takari:maven:wrapper
    - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
    script:
    - "./mvnw test -B"
    - javadoc -d "./doc/backend" -sourcepath src/main/java -subpackages .
    after_script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

  - language: node_js
    node_js:
    - '9'
    name: Frontend
    dist: trusty
    sudo: required
    branches:
      only:
      - frontend_development
    before_script:
    - npm install -g @angular/cli