matrix:
  include:
  - language: java
    jdk: oraclejdk8
    name: Java server
    addons:
      sonarcloud:
        organization: fanni111-github
        token:
          secure: "BtDhFL/16UN/yqjK0o5fVPyPUFqRfmQutAkSWcmPQEsmAfLp66MAHnItEsPH2i99B0exmAlB9PyUB/3uxMPjnJCL6UinpbFgfBk1BM/Ihrjv276beXhwUTiN0ZL2vNdFsXQojki4Lm4GrVQJ8b1Jz0DMMK4xSc1jBWLs8jkOAKJN11ZfXg2e6u3yhE5IeJxyauBcb+h2KpRJHdIucJOA5LDYzJZSXykAcqp6pdnkbRLZ6OJ5tiVXSHPQy4bvO5b1UrlcyU6D+0tDcNipD1qtnC22FaCL8T5C2MKgdMc6V98ICi9DI2yHm8pnQwrS34uZzCBUmGsC1ed18cO/+j94FYRJN8OnYr0c7e13jsRo/MQYOEEYZA4cAjV7d5dNyTfAdVdux703UPf+NMCEiam71HAcY1jm9ZbZIxwof/rGUEqp+fCcH22sKRzeYLLaJuLLaBp4tsWSHAdHeuCQNwjdMRoEfy+8JRfLSuE/uhg9qFmCx1yVLHiaxIB/FMkVSEbsbzuwOYWi8sDlFZtRcmt04h/92W+4o2kJqyrIKcD1CQch2j9TdWoMW9Ncv1Yfw+qJFb44YBQEfUPXzvWf7dL+bZh+aeroPFRFzBsnNGT3joOtyxZ8VF+UiE6Airs9Ar8kTjEsvo1kFXq0Zq+g38b6DHA60FcLtFtZjtumzXfdKFI="
    install:
    - mvn -N io.takari:maven:wrapper
    - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
    script:
    - "./mvnw test -B"
    - javadoc -d "./doc/backend" -sourcepath src/main/java -subpackages .
    after_script:
    #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar\
       -Dsonar.projectKey=Fanni111_Worktable \
       -Dsonar.organization=fanni111-github \
       -Dsonar.host.url=https://sonarqube.com \
       -Dsonar.login=0fb251527833fe6561c570d996188164ca97e8f3
  - language: node_js
    node_js:
    - '9'
    name: Frontend
    dist: trusty
    sudo: required
    branches:
      only:
      - frontend_development
    before_script:
    - npm install -g @angular/cli
