sudo: true
matrix:
  include:
  - language: java
    jdk: oraclejdk8
    name: Java server
    addons:
      sonarcloud:
        organization: fanni111-github
        token:
          secure: "tRnJOVYkHQvN/OBh2R/oF11TVRSpOK93nyi+qIyyPD5Ky2WSXFurSV/4cUpjZ8LfIZovUhfX4K9gm/gUzl4EwnL8i3ufK8XrrVmyXGH8hjt6t30pSBHqEZcDtYtOOd7cWsVgfOsohhhl7W83nT4sfqd2nImrrSFV2LrQhvacu9wZF+eedQQ64PC9WmzPY3QqkWsZP6VYJq+PukAlbNdZIjEN2CLofjI2s4YsNfEoSsUXsTC+JDK83JnGcC3hRw1fbCyfbIvVI4wIBC1bYZOAR3P7Jo+s2tPuDbqevTWZPnKJi147VDiknXV9AIRGireavbG+OePjCG5/j5m1VW486cMvknXvXOoID7eUF/kKET0QA3CrFm2A5aDi3atX/v4ncxN1HEZp8iALHhmqxr2TJmLC6zTfNcLXXTU09demCVPp/eNSHodsdraj8VG3rX6lkvWwpDamuGVFFXjuYgsfUs+xUn8sp6uC76qd8eMRij+kWGU8NaKrYh3uH57I6cOLXbIWqeRV53oVB6acC/2ZNtngOAJlqxFqUG1GvW3zm/UFR9D/IH7CxRCsw6TfFJ1ArnpExZ7asqo3jZXiRNw/YlU6WikpMWZvZ9KGI/b9EM2EoO8Md2rLSmKxklB/QKyXRtiCF3C4z2MTEl3H/q2H9IBcIRuoUe1l/xcLmG6RaRc="
    install:
    - mvn -N io.takari:maven:wrapper
    - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
    script:
    - "./mvnw test -B"
    #- javadoc -d "./doc/backend" -sourcepath src/main/java -subpackages .
    after_script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

    after_success:
    -  javadoc -private -d "./doc/backend" -sourcepath src/main/java -subpackages .
    #- ./javadoc.sh

  - language: node_js
    node_js:
    - '9'
    name: Frontend
    dist: trusty
    sudo: required
    branches:
      only:
      - frontend_development
    before_script:
    - npm install -g @angular/cli
