matrix:
  include:
    - language: java

      addons:
        sonarcloud:
          organization: "fanni111-github"
          token:
            secure: 90be4f30f515d649d7d3cf6f6c3c271eb3bcb0c4

      jdk: oraclejdk8
      name: "Java server"
      install:
      - mvn -N io.takari:maven:wrapper
      - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      branches:

      script:
      - ./mvnw test -B
      mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar -Dsonar.projectKey=Fanni111_Worktable -Dsonar.organization=fanni111-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=d5e00d16e8acc511e50c924995e59725204b87d1

      after_script:
      -  javadoc -d "./doc/backend" -sourcepath src/main/java -subpackages .

    - language: node_js
      node_js:
      - "9"
      name: "Frontend"
      dist: trusty
      sudo: required
      branches:
        only:
        - frontend_development
      before_script:
      - npm install -g @angular/cli
