matrix:
  include:
    - language: java

      addons:
        sonarcloud:
          organization: "worktable"
          token:
            secure: SONAR_TOKEN

      jdk: oraclejdk8
      name: "Java server"
      install:
      - mvn -N io.takari:maven:wrapper
      - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      branches:

      script:
      - ./mvnw test -B
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

      after_script:
      -  javadoc -d "./doc/backend" -sourcepath src/main/java -subpackages .

    - language: node_js
      node_js:
      - "9"
      name: "Frontend"
      dist: trusty
      sudo: required
      branches:
        only:
        - frontend_development
      before_script:
      - npm install -g @angular/cli
